#!/bin/bash
if show=$(bundle show); then
  l1=$(echo "$show" | awk '{print $2}')
else
  l1=$(echo "$show" | awk '{gsub("-","_",$18); print $18}')
fi
l3=`comm -12 <(bundle config | grep 'local\.' | awk -F '.' '{print $2}' | sort -u) <(echo "$l1" | sort -u)`
git checkout -- Gemfile.lock
for i in $l3; do
  (
    cd "../${i//_/-}"
    git pull
  )
done
git pull
