#!/bin/zsh
set -e
declare -a git_gems
git_gems=()
bundle show | awk '/^* (.*) \(.* .*\)/ { print $2; }' | while read line ; do git_gems+=($line) ; done
cmd="rerun -s SIGUSR2 --pattern '{**/*.{rb,ru,json,txt,scss,sass},Gemfile,Gemfile.lock,Rakefile,*.gemspec,.env}' --dir '."
for i in "${git_gems[@]}"; do
  gem_path=$(bundle show "$i")
  cmd+=",$gem_path"
done
if [[ -f config.ru ]]; then
  cmd+="' foreman start web"
else
  cmd+="' foreman start worker"
fi
echo $cmd
eval $cmd
