#!/bin/zsh
set -e
declare -a git_gems
git_gems=()
bundle show | awk '/^* (.*) \(.* .*\)/ { print $2; }' | while read line ; do git_gems+=($line) ; done
cmd="rerun -s SIGTERM --pattern '{**/*.{rb,ru,json,txt},Gemfile,Gemfile.lock,Rakefile,*.gemspec,.env}' --dir '."
for i in "${git_gems[@]}"; do
  gem_path=$(bundle show "$i")
  cmd+=",$gem_path"
done
cmd+="' 'foreman start -m all=1,release=0'"
echo $cmd
eval $cmd
